version: "2"

volumes:
    portainer: {}

services:
  portainer:
    image: portainer/portainer
    command: --host=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
      - "9000:9000"